# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class TopicProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    knowledge_level: Literal["beginner", "intermediate", "advanced"] | None = None
    confirmed_gaps: list[str] | None = []
    mastered_concepts: list[str] | None = []
    focus_target_gap: str | None = None
    last_session_summary: str | None = None


class Citation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    doc_id: str
    text: str
    page: int | None = None
    doc_name: str | None = None


class ToolCallRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    args: dict[str, Any]
    status: Literal["ok", "failed", "no_results"]
    error: str | None = None


class LearningEventResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: int
    session_id: str
    gap_tested: str
    question: str
    correct: bool
    created_at: datetime


class UpdateTopicProfileArgs(BaseModel):
    """
    Patch operation for a session's TopicProfile. Sending
    `focus_target_gap: null` explicitly clears focus and requires
    `focus_clear_reason` (server-side guard rail). `evidence_type` is
    required only when `add_mastered_concept` is present.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: constr(max_length=64)
    knowledge_level: Literal["beginner", "intermediate", "advanced"] | None = None
    add_confirmed_gap: constr(max_length=200) | None = None
    add_mastered_concept: constr(max_length=200) | None = None
    focus_target_gap: constr(max_length=200) | None = None
    focus_clear_reason: (
        Literal["demonstrated", "tested_correct", "user_redirected"] | None
    ) = None
    evidence_type: Literal["declared", "inferred", "tested"] | None = None


class RetrieveChunksArgs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: constr(max_length=64)
    query: constr(max_length=500)
    k: conint(ge=1, le=20) | None = 5


class RecordLearningEventArgs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: constr(max_length=64)
    gap_tested: constr(max_length=200)
    question: constr(max_length=1000)
    correct: bool


class AskCheckQuestionArgs(BaseModel):
    """
    Register an open multiple-choice check-question and end the turn. The
    question text is also streamed to the learner as normal assistant text.
    options/correct_index/explanation drive the interactive card and the
    server-side deterministic grade. correct_index must be < len(options);
    this cross-field rule is enforced in check_question_service, not here.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: constr(max_length=64)
    gap: constr(max_length=200)
    question: constr(max_length=1000)
    options: list[constr(max_length=200)] = Field(..., max_length=4, min_length=2)
    correct_index: conint(ge=0)
    explanation: constr(max_length=500)


class PendingCheck(BaseModel):
    """
    An open check-question awaiting a learner answer. PUBLIC projection:
    never carries correct_index or explanation.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    gap: str
    question: str
    options: list[str]


class CheckAnswerRequest(BaseModel):
    """
    A learner's clicked answer to the open check-question.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    selected_index: conint(ge=0)


class CheckAnswerResponse(BaseModel):
    """
    Deterministic grade of a clicked check-question answer.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    correct: bool
    explanation: str
    correct_index: int


class ToolResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: bool
    status: Literal["ok", "failed", "no_results"]
    error: str | None = None
    data: dict[str, Any] | None = None


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: str


class ChatRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: constr(max_length=64)
    message: constr(max_length=4000)


class ChatResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assistant_message: str
    message_id: int
    tool_calls: list[ToolCallRecord] | None = []
    citations: list[Citation] | None = []
    pending_check: PendingCheck | None = None


class SessionCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    topic: constr(max_length=200)
    seed_mode: Literal["fresh", "resume"]
    prior_session_id: constr(max_length=64) | None = None


class SessionUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    topic: constr(max_length=200) | None = None
    pinned: bool | None = None


class SessionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    user_id: str
    topic: str
    topic_profile: TopicProfile
    created_at: datetime
    ended_at: datetime | None = None
    ingestion_status: Literal["pending", "ready", "failed"] | None = None
    pinned: bool | None = False


class SessionListItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    topic: str
    created_at: datetime
    ended_at: datetime | None = None
    pinned: bool | None = False


class Message(BaseModel):
    """
    A single chat turn persisted in the session transcript.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: int
    role: str
    content: str
    created_at: datetime
    citations: list[Citation] | None = []
    tool_calls: list[ToolCallRecord] | None = []


class SessionDetail(BaseModel):
    """
    SessionResponse plus full message transcript.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    user_id: str
    topic: str
    topic_profile: TopicProfile
    created_at: datetime
    ended_at: datetime | None = None
    ingestion_status: Literal["pending", "ready", "failed"] | None = None
    pinned: bool | None = False
    pending_check: PendingCheck | None = None
    messages: list[Message]


class SessionEndSummary(BaseModel):
    """
    Structured payload describing how a session ended. Frontend branches on
    `kind` to render friendly copy. Legacy [auto] strings have been removed.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["summary", "no_exchanges"]
    text: str


class SessionEndResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    ended_at: datetime
    summary: SessionEndSummary


class UploadResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    document_id: int
    session_id: str
    filename: str
    status: Literal["pending", "ready", "failed"]


class UploadStatus(BaseModel):
    """
    Ingestion state for an uploaded document; polled by the UI.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: int
    status: Literal["pending", "ready", "failed"]
    error: str | None = None


class ProfileResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile: TopicProfile
    recent_learning_events: list[LearningEventResponse]


class AggregateConceptCount(BaseModel):
    """
    Concept (mastered or gap) plus how many sessions it appears in and the
    earliest session id where it was recorded.

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    concept: str
    count: conint(ge=1)
    first_seen_session_id: str


class KnowledgeLevelDistribution(BaseModel):
    """
    Count of sessions per knowledge_level (unknown = null knowledge_level).

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    beginner: conint(ge=0)
    intermediate: conint(ge=0)
    advanced: conint(ge=0)
    unknown: conint(ge=0)


class RecentSessionSummary(BaseModel):
    """
    Compact session header for the "recent topics" widget.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    topic: str
    created_at: datetime
    ended_at: datetime | None = None
    last_session_summary: str | None = None


class AggregateProfileResponse(BaseModel):
    """
    Cross-session aggregate view powering the top-level /profile dashboard.
    All arrays are sorted by count desc (mastered + gaps) or created_at desc
    (recent_topics).

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    total_sessions: conint(ge=0)
    active_sessions: conint(ge=0)
    ended_sessions: conint(ge=0)
    total_learning_events: conint(ge=0)
    last_active_at: datetime | None = None
    combined_mastered_concepts: list[AggregateConceptCount]
    combined_confirmed_gaps: list[AggregateConceptCount]
    knowledge_level_distribution: KnowledgeLevelDistribution
    recent_topics: list[RecentSessionSummary]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail: str
