# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, RootModel, conint


class TopicProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    knowledge_level: Literal["beginner", "intermediate", "advanced"] | None = None
    confirmed_gaps: list[str] | None = []
    mastered_concepts: list[str] | None = []
    focus_target_gap: str | None = None
    last_session_summary: str | None = None


class Citation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    doc_id: str
    text: str


class ToolCallRecord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    args: dict[str, Any]
    status: Literal["ok", "failed", "no_results"]
    error: str | None = None


class LearningEventResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: int
    session_id: str
    gap_tested: str
    question: str
    correct: bool
    created_at: datetime


class UpdateTopicProfileArgs(BaseModel):
    """
    Patch operation for a session's TopicProfile. Sending
    `focus_target_gap: null` explicitly clears focus and requires
    `focus_clear_reason` (server-side guard rail).

    """

    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: str
    knowledge_level: Literal["beginner", "intermediate", "advanced"] | None = None
    add_confirmed_gap: str | None = None
    add_mastered_concept: str | None = None
    focus_target_gap: str | None = None
    focus_clear_reason: (
        Literal["demonstrated", "tested_correct", "user_redirected"] | None
    ) = None
    evidence_type: Literal["declared", "inferred", "tested"]


class RetrieveChunksArgs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: str
    query: str
    k: conint(ge=1, le=20) | None = 5


class RecordLearningEventArgs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: str
    gap_tested: str
    question: str
    correct: bool


class ToolResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: bool
    status: Literal["ok", "failed", "no_results"]
    error: str | None = None
    data: dict[str, Any] | None = None


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: str


class ChatRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_id: str
    session_id: str
    message: str


class ChatResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    assistant_message: str
    message_id: int
    tool_calls: list[ToolCallRecord] | None = []
    citations: list[Citation] | None = []


class SessionCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_id: str
    topic: str
    seed_mode: Literal["fresh", "resume"]
    prior_session_id: str | None = None


class SessionResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    user_id: str
    topic: str
    topic_profile: TopicProfile
    created_at: datetime
    ended_at: datetime | None = None
    ingestion_status: Literal["pending", "ready", "failed"] | None = None


class SessionListItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    topic: str
    created_at: datetime
    ended_at: datetime | None = None


class SessionEndResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    ended_at: datetime
    summary: str


class UploadResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    document_id: int
    session_id: str
    filename: str
    status: Literal["pending", "ready", "failed"]


class ProfileResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    profile: TopicProfile
    recent_learning_events: list[LearningEventResponse]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail: str
